if(ENABLE_CLANG_TIDY)
    find_program(CLANG_TIDY_COMMAND NAMES clang-tidy)

    if(NOT CLANG_TIDY_COMMAND)
        message(WARNING "❌ ​CMake_RUN_CLANG_TIDY is ON but clang-tidy is not found!")
        set(CMAKE_C_CLANG_TIDY "" CACHE STRING "" FORCE)
        set(CMAKE_CXX_CLANG_TIDY "" CACHE STRING "" FORCE)
    else()
        message(STATUS "✅​ CMake_RUN_CLANG_TIDY is ON. Path: ${CLANG_TIDY_COMMAND}")
        set(C_CLANG_TIDY_EXTRA_ARGS "-std=c17")
        set(CXX_CLANG_TIDY_EXTRA_ARGS "-std=c++17")
        set(CMAKE_C_CLANG_TIDY "${CLANG_TIDY_COMMAND};-p=${CMAKE_BINARY_DIR};-extra-arg=${C_CLANG_TIDY_EXTRA_ARGS}" CACHE STRING "" FORCE)
        set(CMAKE_CXX_CLANG_TIDY "${CLANG_TIDY_COMMAND};-p=${CMAKE_BINARY_DIR};-extra-arg=${CXX_CLANG_TIDY_EXTRA_ARGS}" CACHE STRING "" FORCE)
        set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
        configure_file(cmake/Build.clang-tidy.in .clang-tidy)
    endif()
endif()
